### ISSUE TITLE
Feature request: docker exec support. 

### ISSUE THREAD

**Issue by mehmetg** [criteo/mesos-term#43]
What do you think it'll take to add docker exec support ?

**Comment by clems4ever** [comment]
Hello @mehmetg , I think it comes down to how Mesos handles nested containers using the docker engine and what is required by the API to make it work but I don't know exactly.
MesosTerm is built on top of a set of Python scripts produced by former Mesosphere doing the interface between MesosTerm and the Mesos cluster. I reused this piece of code mainly to avoid rewriting the interactive tty myself but it also handles all the API calls. You can find the scripts here: https://github.com/clems4ever/mesos-term/tree/master/src/python.

If you can confirm that Mesos supports nested containers leveraging the docker engine, it should be easy to adapt the API call. The code is here if you want to have a look: https://github.com/clems4ever/mesos-term/blob/4a86f6b215e223789c200052133c999befd8de17/src/python/mesos/mesos.py#L622.

**Comment by kamaradclimber** [comment]
Hello @mehmetg , I'm closing this issue but feel free to reopen or propose a patch, we'd be happy to consider it.
